import { Weather } from "./weather";

export const MockWeather: Weather = {
    "latitude": 37.8267,
    "longitude": -122.4233,
    "timezone": "America/Los_Angeles",
    "offset": -7,
    "currently": {
        "time": 1496755543,
        "summary": "Mostly Cloudy",
        "icon": "partly-cloudy-day",
        "nearestStormDistance": 251,
        "nearestStormBearing": 164,
        "precipIntensity": 0,
        "precipProbability": 0,
        "temperature": 52.77,
        "apparentTemperature": 52.77,
        "dewPoint": 50.01,
        "humidity": 0.9,
        "windSpeed": 7.35,
        "windBearing": 256,
        "visibility": 9.3,
        "cloudCover": 0.66,
        "pressure": 1013.03,
        "ozone": 318.69
    },
    "minutely": {
        "summary": "Mostly cloudy for the hour.",
        "icon": "partly-cloudy-day",
        "data": [
            {
                "time": 1496755500,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496755560,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496755620,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496755680,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496755740,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496755800,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496755860,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496755920,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496755980,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496756040,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496756100,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496756160,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496756220,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496756280,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496756340,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496756400,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496756460,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496756520,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496756580,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496756640,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496756700,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496756760,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496756820,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496756880,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496756940,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496757000,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496757060,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496757120,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496757180,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496757240,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496757300,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496757360,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496757420,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496757480,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496757540,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496757600,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496757660,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496757720,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496757780,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496757840,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496757900,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496757960,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496758020,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496758080,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496758140,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496758200,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496758260,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496758320,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496758380,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496758440,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496758500,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496758560,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496758620,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496758680,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496758740,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496758800,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496758860,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496758920,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496758980,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496759040,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1496759100,
                "precipIntensity": 0,
                "precipProbability": 0
            }
        ]
    },
    "hourly": {
        "summary": "Partly cloudy throughout the day.",
        "icon": "partly-cloudy-day",
        "data": [
            {
                "time": 1496754000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 52.77,
                "apparentTemperature": 52.77,
                "dewPoint": 50.22,
                "humidity": 0.91,
                "windSpeed": 6.58,
                "windBearing": 254,
                "visibility": 9.26,
                "cloudCover": 0.65,
                "pressure": 1013,
                "ozone": 318.28
            },
            {
                "time": 1496757600,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 53.83,
                "apparentTemperature": 53.83,
                "dewPoint": 50.78,
                "humidity": 0.89,
                "windSpeed": 8.38,
                "windBearing": 257,
                "visibility": 9.37,
                "cloudCover": 0.67,
                "pressure": 1013.07,
                "ozone": 319.24
            },
            {
                "time": 1496761200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0014,
                "precipProbability": 0.03,
                "precipType": "rain",
                "temperature": 55.48,
                "apparentTemperature": 55.48,
                "dewPoint": 51.29,
                "humidity": 0.86,
                "windSpeed": 8.42,
                "windBearing": 262,
                "visibility": 9.57,
                "cloudCover": 0.76,
                "pressure": 1013.23,
                "ozone": 320.12
            },
            {
                "time": 1496764800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0012,
                "precipProbability": 0.02,
                "precipType": "rain",
                "temperature": 57.15,
                "apparentTemperature": 57.15,
                "dewPoint": 51.6,
                "humidity": 0.82,
                "windSpeed": 8.58,
                "windBearing": 265,
                "visibility": 9.69,
                "cloudCover": 0.75,
                "pressure": 1013.46,
                "ozone": 320.93
            },
            {
                "time": 1496768400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 58.98,
                "apparentTemperature": 58.98,
                "dewPoint": 51.9,
                "humidity": 0.77,
                "windSpeed": 8.9,
                "windBearing": 266,
                "visibility": 9.74,
                "cloudCover": 0.57,
                "pressure": 1013.7,
                "ozone": 321.66
            },
            {
                "time": 1496772000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 61.07,
                "apparentTemperature": 61.07,
                "dewPoint": 52.46,
                "humidity": 0.73,
                "windSpeed": 9.3,
                "windBearing": 265,
                "visibility": 9.82,
                "cloudCover": 0.36,
                "pressure": 1013.85,
                "ozone": 321.86
            },
            {
                "time": 1496775600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 63.73,
                "apparentTemperature": 63.73,
                "dewPoint": 53.02,
                "humidity": 0.68,
                "windSpeed": 9.14,
                "windBearing": 269,
                "visibility": 9.88,
                "cloudCover": 0.33,
                "pressure": 1013.94,
                "ozone": 321.15
            },
            {
                "time": 1496779200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 65.6,
                "apparentTemperature": 65.6,
                "dewPoint": 53.62,
                "humidity": 0.65,
                "windSpeed": 9.86,
                "windBearing": 270,
                "visibility": 9.91,
                "cloudCover": 0.3,
                "pressure": 1013.81,
                "ozone": 319.91
            },
            {
                "time": 1496782800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 66.44,
                "apparentTemperature": 66.44,
                "dewPoint": 53.78,
                "humidity": 0.64,
                "windSpeed": 10.55,
                "windBearing": 272,
                "visibility": 9.92,
                "cloudCover": 0.27,
                "pressure": 1013.64,
                "ozone": 318.85
            },
            {
                "time": 1496786400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 66.57,
                "apparentTemperature": 66.57,
                "dewPoint": 53.68,
                "humidity": 0.63,
                "windSpeed": 11.06,
                "windBearing": 273,
                "visibility": 9.93,
                "cloudCover": 0.33,
                "pressure": 1013.42,
                "ozone": 318.21
            },
            {
                "time": 1496790000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 65.6,
                "apparentTemperature": 65.6,
                "dewPoint": 53.07,
                "humidity": 0.64,
                "windSpeed": 11.5,
                "windBearing": 275,
                "visibility": 9.93,
                "cloudCover": 0.33,
                "pressure": 1013.19,
                "ozone": 317.76
            },
            {
                "time": 1496793600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 64.16,
                "apparentTemperature": 64.16,
                "dewPoint": 52.24,
                "humidity": 0.65,
                "windSpeed": 11.66,
                "windBearing": 277,
                "visibility": 9.93,
                "cloudCover": 0.33,
                "pressure": 1013.03,
                "ozone": 317.43
            },
            {
                "time": 1496797200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 62.37,
                "apparentTemperature": 62.37,
                "dewPoint": 51.76,
                "humidity": 0.68,
                "windSpeed": 11.46,
                "windBearing": 278,
                "visibility": 9.93,
                "cloudCover": 0.34,
                "pressure": 1012.94,
                "ozone": 317.3
            },
            {
                "time": 1496800800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 60.02,
                "apparentTemperature": 60.02,
                "dewPoint": 51.29,
                "humidity": 0.73,
                "windSpeed": 11.03,
                "windBearing": 279,
                "visibility": 9.93,
                "cloudCover": 0.35,
                "pressure": 1012.9,
                "ozone": 317.3
            },
            {
                "time": 1496804400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 57.98,
                "apparentTemperature": 57.98,
                "dewPoint": 50.6,
                "humidity": 0.76,
                "windSpeed": 10.49,
                "windBearing": 280,
                "visibility": 9.91,
                "cloudCover": 0.51,
                "pressure": 1012.96,
                "ozone": 317.18
            },
            {
                "time": 1496808000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 56.48,
                "apparentTemperature": 56.48,
                "dewPoint": 50.39,
                "humidity": 0.8,
                "windSpeed": 9.79,
                "windBearing": 280,
                "visibility": 9.81,
                "cloudCover": 0.46,
                "pressure": 1013.19,
                "ozone": 316.81
            },
            {
                "time": 1496811600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 55.57,
                "apparentTemperature": 55.57,
                "dewPoint": 50.49,
                "humidity": 0.83,
                "windSpeed": 9.17,
                "windBearing": 281,
                "visibility": 9.78,
                "cloudCover": 0.47,
                "pressure": 1013.51,
                "ozone": 316.32
            },
            {
                "time": 1496815200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 55.33,
                "apparentTemperature": 55.33,
                "dewPoint": 50.84,
                "humidity": 0.85,
                "windSpeed": 8.83,
                "windBearing": 281,
                "visibility": 9.88,
                "cloudCover": 0.38,
                "pressure": 1013.72,
                "ozone": 315.81
            },
            {
                "time": 1496818800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 54.63,
                "apparentTemperature": 54.63,
                "dewPoint": 50.61,
                "humidity": 0.86,
                "windSpeed": 8.5,
                "windBearing": 280,
                "visibility": 9.94,
                "cloudCover": 0.54,
                "pressure": 1013.68,
                "ozone": 315.21
            },
            {
                "time": 1496822400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 54.46,
                "apparentTemperature": 54.46,
                "dewPoint": 50.59,
                "humidity": 0.87,
                "windSpeed": 8.18,
                "windBearing": 277,
                "visibility": 9.97,
                "cloudCover": 0.54,
                "pressure": 1013.51,
                "ozone": 314.59
            },
            {
                "time": 1496826000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 54.22,
                "apparentTemperature": 54.22,
                "dewPoint": 50.35,
                "humidity": 0.87,
                "windSpeed": 7.98,
                "windBearing": 275,
                "visibility": 9.98,
                "cloudCover": 0.61,
                "pressure": 1013.34,
                "ozone": 314.2
            },
            {
                "time": 1496829600,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 53.37,
                "apparentTemperature": 53.37,
                "dewPoint": 50.03,
                "humidity": 0.88,
                "windSpeed": 7.96,
                "windBearing": 272,
                "visibility": 10,
                "cloudCover": 0.62,
                "pressure": 1013.17,
                "ozone": 314.1
            },
            {
                "time": 1496833200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0012,
                "precipProbability": 0.02,
                "precipType": "rain",
                "temperature": 52.75,
                "apparentTemperature": 52.75,
                "dewPoint": 49.57,
                "humidity": 0.89,
                "windSpeed": 8.1,
                "windBearing": 271,
                "visibility": 10,
                "cloudCover": 0.63,
                "pressure": 1013,
                "ozone": 314.23
            },
            {
                "time": 1496836800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0016,
                "precipProbability": 0.03,
                "precipType": "rain",
                "temperature": 52.43,
                "apparentTemperature": 52.43,
                "dewPoint": 49.28,
                "humidity": 0.89,
                "windSpeed": 8.22,
                "windBearing": 270,
                "visibility": 10,
                "cloudCover": 0.64,
                "pressure": 1012.96,
                "ozone": 314.67
            },
            {
                "time": 1496840400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0012,
                "precipProbability": 0.02,
                "precipType": "rain",
                "temperature": 52.82,
                "apparentTemperature": 52.82,
                "dewPoint": 49.92,
                "humidity": 0.9,
                "windSpeed": 8.29,
                "windBearing": 270,
                "visibility": 10,
                "cloudCover": 0.56,
                "pressure": 1013.14,
                "ozone": 315.61
            },
            {
                "time": 1496844000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 53.37,
                "apparentTemperature": 53.37,
                "dewPoint": 50.21,
                "humidity": 0.89,
                "windSpeed": 8.36,
                "windBearing": 269,
                "visibility": 10,
                "cloudCover": 0.54,
                "pressure": 1013.42,
                "ozone": 316.86
            },
            {
                "time": 1496847600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 54.49,
                "apparentTemperature": 54.49,
                "dewPoint": 50.64,
                "humidity": 0.87,
                "windSpeed": 8.43,
                "windBearing": 268,
                "visibility": 10,
                "cloudCover": 0.53,
                "pressure": 1013.68,
                "ozone": 318.01
            },
            {
                "time": 1496851200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 56.49,
                "apparentTemperature": 56.49,
                "dewPoint": 51.37,
                "humidity": 0.83,
                "windSpeed": 8.46,
                "windBearing": 264,
                "visibility": 10,
                "cloudCover": 0.48,
                "pressure": 1013.85,
                "ozone": 319.03
            },
            {
                "time": 1496854800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 58.58,
                "apparentTemperature": 58.58,
                "dewPoint": 51.76,
                "humidity": 0.78,
                "windSpeed": 8.51,
                "windBearing": 260,
                "visibility": 10,
                "cloudCover": 0.41,
                "pressure": 1013.98,
                "ozone": 319.96
            },
            {
                "time": 1496858400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 60.37,
                "apparentTemperature": 60.37,
                "dewPoint": 51.77,
                "humidity": 0.73,
                "windSpeed": 8.74,
                "windBearing": 258,
                "visibility": 10,
                "cloudCover": 0.35,
                "pressure": 1014.05,
                "ozone": 320.42
            },
            {
                "time": 1496862000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 62.08,
                "apparentTemperature": 62.08,
                "dewPoint": 51.81,
                "humidity": 0.69,
                "windSpeed": 9.42,
                "windBearing": 261,
                "visibility": 10,
                "cloudCover": 0.4,
                "pressure": 1014.03,
                "ozone": 320.21
            },
            {
                "time": 1496865600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 64.03,
                "apparentTemperature": 64.03,
                "dewPoint": 52.12,
                "humidity": 0.65,
                "windSpeed": 10.5,
                "windBearing": 264,
                "visibility": 10,
                "cloudCover": 0.48,
                "pressure": 1013.94,
                "ozone": 319.54
            },
            {
                "time": 1496869200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 65.53,
                "apparentTemperature": 65.53,
                "dewPoint": 52.79,
                "humidity": 0.63,
                "windSpeed": 11.45,
                "windBearing": 266,
                "visibility": 10,
                "cloudCover": 0.56,
                "pressure": 1013.81,
                "ozone": 318.65
            },
            {
                "time": 1496872800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 66.15,
                "apparentTemperature": 66.15,
                "dewPoint": 53.95,
                "humidity": 0.65,
                "windSpeed": 12.07,
                "windBearing": 268,
                "visibility": 10,
                "cloudCover": 0.6,
                "pressure": 1013.63,
                "ozone": 317.4
            },
            {
                "time": 1496876400,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 65.62,
                "apparentTemperature": 65.62,
                "dewPoint": 54.85,
                "humidity": 0.68,
                "windSpeed": 12.44,
                "windBearing": 270,
                "visibility": 10,
                "cloudCover": 0.63,
                "pressure": 1013.45,
                "ozone": 315.94
            },
            {
                "time": 1496880000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 64.55,
                "apparentTemperature": 64.55,
                "dewPoint": 55.3,
                "humidity": 0.72,
                "windSpeed": 12.32,
                "windBearing": 271,
                "visibility": 10,
                "cloudCover": 0.69,
                "pressure": 1013.35,
                "ozone": 314.87
            },
            {
                "time": 1496883600,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 62.76,
                "apparentTemperature": 62.76,
                "dewPoint": 55.03,
                "humidity": 0.76,
                "windSpeed": 11.5,
                "windBearing": 271,
                "visibility": 9.98,
                "cloudCover": 0.78,
                "pressure": 1013.41,
                "ozone": 314.48
            },
            {
                "time": 1496887200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 60.54,
                "apparentTemperature": 60.54,
                "dewPoint": 54.4,
                "humidity": 0.8,
                "windSpeed": 10.22,
                "windBearing": 270,
                "visibility": 9.92,
                "cloudCover": 0.89,
                "pressure": 1013.55,
                "ozone": 314.49
            },
            {
                "time": 1496890800,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 58.64,
                "apparentTemperature": 58.64,
                "dewPoint": 53.84,
                "humidity": 0.84,
                "windSpeed": 8.8,
                "windBearing": 268,
                "visibility": 9.67,
                "cloudCover": 0.98,
                "pressure": 1013.74,
                "ozone": 314.75
            },
            {
                "time": 1496894400,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 57.67,
                "apparentTemperature": 57.67,
                "dewPoint": 53.86,
                "humidity": 0.87,
                "windSpeed": 7.31,
                "windBearing": 263,
                "visibility": 9.07,
                "cloudCover": 1,
                "pressure": 1014.01,
                "ozone": 315.39
            },
            {
                "time": 1496898000,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 57.09,
                "apparentTemperature": 57.09,
                "dewPoint": 54.07,
                "humidity": 0.9,
                "windSpeed": 5.86,
                "windBearing": 253,
                "visibility": 8.28,
                "cloudCover": 0.99,
                "pressure": 1014.32,
                "ozone": 316.27
            },
            {
                "time": 1496901600,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 56.67,
                "apparentTemperature": 56.67,
                "dewPoint": 54.24,
                "humidity": 0.92,
                "windSpeed": 4.98,
                "windBearing": 241,
                "visibility": 7.61,
                "cloudCover": 0.99,
                "pressure": 1014.52,
                "ozone": 316.75
            },
            {
                "time": 1496905200,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 56.52,
                "apparentTemperature": 56.52,
                "dewPoint": 54.48,
                "humidity": 0.93,
                "windSpeed": 4.69,
                "windBearing": 232,
                "visibility": 7.19,
                "cloudCover": 0.99,
                "pressure": 1014.52,
                "ozone": 316.56
            },
            {
                "time": 1496908800,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 56.49,
                "apparentTemperature": 56.49,
                "dewPoint": 54.66,
                "humidity": 0.94,
                "windSpeed": 4.83,
                "windBearing": 226,
                "visibility": 6.89,
                "cloudCover": 0.99,
                "pressure": 1014.42,
                "ozone": 315.96
            },
            {
                "time": 1496912400,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 56.34,
                "apparentTemperature": 56.34,
                "dewPoint": 54.66,
                "humidity": 0.94,
                "windSpeed": 4.97,
                "windBearing": 220,
                "visibility": 6.57,
                "cloudCover": 0.99,
                "pressure": 1014.32,
                "ozone": 315.14
            },
            {
                "time": 1496916000,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 55.85,
                "apparentTemperature": 55.85,
                "dewPoint": 54.32,
                "humidity": 0.95,
                "windSpeed": 5.05,
                "windBearing": 212,
                "visibility": 6.04,
                "cloudCover": 0.97,
                "pressure": 1014.22,
                "ozone": 314.05
            },
            {
                "time": 1496919600,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 55.19,
                "apparentTemperature": 55.19,
                "dewPoint": 53.75,
                "humidity": 0.95,
                "windSpeed": 5.21,
                "windBearing": 205,
                "visibility": 5.49,
                "cloudCover": 0.94,
                "pressure": 1014.13,
                "ozone": 312.75
            },
            {
                "time": 1496923200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 54.82,
                "apparentTemperature": 54.82,
                "dewPoint": 53.23,
                "humidity": 0.94,
                "windSpeed": 5.5,
                "windBearing": 200,
                "visibility": 5.39,
                "cloudCover": 0.91,
                "pressure": 1014.11,
                "ozone": 311.52
            },
            {
                "time": 1496926800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0015,
                "precipProbability": 0.03,
                "precipType": "rain",
                "temperature": 55.79,
                "apparentTemperature": 55.79,
                "dewPoint": 53.75,
                "humidity": 0.93,
                "windSpeed": 6,
                "windBearing": 196,
                "visibility": 6.14,
                "cloudCover": 0.88,
                "pressure": 1014.21,
                "ozone": 310.56
            }
        ]
    },
    "daily": {
        "summary": "Light rain on Thursday, with temperatures bottoming out at 60°F on Saturday.",
        "icon": "rain",
        "data": [
            {
                "time": 1496732400,
                "summary": "Partly cloudy throughout the day.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1496753352,
                "sunsetTime": 1496806234,
                "moonPhase": 0.42,
                "precipIntensity": 0.0001,
                "precipIntensityMax": 0.0014,
                "precipIntensityMaxTime": 1496761200,
                "precipProbability": 0.03,
                "precipType": "rain",
                "temperatureMin": 51.71,
                "temperatureMinTime": 1496743200,
                "temperatureMax": 66.57,
                "temperatureMaxTime": 1496786400,
                "apparentTemperatureMin": 51.71,
                "apparentTemperatureMinTime": 1496743200,
                "apparentTemperatureMax": 66.57,
                "apparentTemperatureMaxTime": 1496786400,
                "dewPoint": 51.22,
                "humidity": 0.79,
                "windSpeed": 8.69,
                "windBearing": 270,
                "visibility": 9.69,
                "cloudCover": 0.41,
                "pressure": 1013.17,
                "ozone": 318.59
            },
            {
                "time": 1496818800,
                "summary": "Mostly cloudy throughout the day.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1496839740,
                "sunsetTime": 1496892667,
                "moonPhase": 0.45,
                "precipIntensity": 0.0003,
                "precipIntensityMax": 0.0016,
                "precipIntensityMaxTime": 1496836800,
                "precipProbability": 0.03,
                "precipType": "rain",
                "temperatureMin": 52.43,
                "temperatureMinTime": 1496836800,
                "temperatureMax": 66.15,
                "temperatureMaxTime": 1496872800,
                "apparentTemperatureMin": 52.43,
                "apparentTemperatureMinTime": 1496836800,
                "apparentTemperatureMax": 66.15,
                "apparentTemperatureMaxTime": 1496872800,
                "dewPoint": 52.18,
                "humidity": 0.81,
                "windSpeed": 8.96,
                "windBearing": 267,
                "visibility": 9.77,
                "cloudCover": 0.64,
                "pressure": 1013.65,
                "ozone": 316.49
            },
            {
                "time": 1496905200,
                "summary": "Light rain starting in the afternoon, continuing until evening.",
                "icon": "rain",
                "sunriseTime": 1496926130,
                "sunsetTime": 1496979099,
                "moonPhase": 0.47,
                "precipIntensity": 0.0038,
                "precipIntensityMax": 0.0095,
                "precipIntensityMaxTime": 1496966400,
                "precipProbability": 0.5,
                "precipType": "rain",
                "temperatureMin": 54.82,
                "temperatureMinTime": 1496923200,
                "temperatureMax": 65.7,
                "temperatureMaxTime": 1496948400,
                "apparentTemperatureMin": 54.82,
                "apparentTemperatureMinTime": 1496923200,
                "apparentTemperatureMax": 65.7,
                "apparentTemperatureMaxTime": 1496948400,
                "dewPoint": 56.08,
                "humidity": 0.88,
                "windSpeed": 6.38,
                "windBearing": 221,
                "visibility": 8.6,
                "cloudCover": 0.83,
                "pressure": 1014.82,
                "ozone": 306.67
            },
            {
                "time": 1496991600,
                "summary": "Mostly cloudy in the morning.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1497012521,
                "sunsetTime": 1497065530,
                "moonPhase": 0.51,
                "precipIntensity": 0.0005,
                "precipIntensityMax": 0.0033,
                "precipIntensityMaxTime": 1496991600,
                "precipProbability": 0.11,
                "precipType": "rain",
                "temperatureMin": 52.54,
                "temperatureMinTime": 1497074400,
                "temperatureMax": 63.62,
                "temperatureMaxTime": 1497042000,
                "apparentTemperatureMin": 52.54,
                "apparentTemperatureMinTime": 1497074400,
                "apparentTemperatureMax": 63.62,
                "apparentTemperatureMaxTime": 1497042000,
                "dewPoint": 50.49,
                "humidity": 0.78,
                "windSpeed": 10.07,
                "windBearing": 277,
                "visibility": 10,
                "cloudCover": 0.39,
                "pressure": 1015.29,
                "ozone": 315.32
            },
            {
                "time": 1497078000,
                "summary": "Clear throughout the day.",
                "icon": "clear-day",
                "sunriseTime": 1497098914,
                "sunsetTime": 1497151960,
                "moonPhase": 0.54,
                "precipIntensity": 0,
                "precipIntensityMax": 0,
                "precipProbability": 0,
                "temperatureMin": 51.81,
                "temperatureMinTime": 1497092400,
                "temperatureMax": 59.98,
                "temperatureMaxTime": 1497135600,
                "apparentTemperatureMin": 51.81,
                "apparentTemperatureMinTime": 1497092400,
                "apparentTemperatureMax": 59.98,
                "apparentTemperatureMaxTime": 1497135600,
                "dewPoint": 44.83,
                "humidity": 0.7,
                "windSpeed": 10.25,
                "windBearing": 275,
                "cloudCover": 0,
                "pressure": 1016.64,
                "ozone": 327.76
            },
            {
                "time": 1497164400,
                "summary": "Clear throughout the day.",
                "icon": "clear-day",
                "sunriseTime": 1497185309,
                "sunsetTime": 1497238388,
                "moonPhase": 0.57,
                "precipIntensity": 0,
                "precipIntensityMax": 0,
                "precipProbability": 0,
                "temperatureMin": 51.31,
                "temperatureMinTime": 1497182400,
                "temperatureMax": 63.79,
                "temperatureMaxTime": 1497218400,
                "apparentTemperatureMin": 51.31,
                "apparentTemperatureMinTime": 1497182400,
                "apparentTemperatureMax": 63.79,
                "apparentTemperatureMaxTime": 1497218400,
                "dewPoint": 43.03,
                "humidity": 0.62,
                "windSpeed": 8.67,
                "windBearing": 285,
                "cloudCover": 0,
                "pressure": 1015.99,
                "ozone": 346.6
            },
            {
                "time": 1497250800,
                "summary": "Clear throughout the day.",
                "icon": "clear-day",
                "sunriseTime": 1497271706,
                "sunsetTime": 1497324814,
                "moonPhase": 0.6,
                "precipIntensity": 0,
                "precipIntensityMax": 0,
                "precipProbability": 0,
                "temperatureMin": 53.4,
                "temperatureMinTime": 1497268800,
                "temperatureMax": 64.66,
                "temperatureMaxTime": 1497308400,
                "apparentTemperatureMin": 53.4,
                "apparentTemperatureMinTime": 1497268800,
                "apparentTemperatureMax": 64.66,
                "apparentTemperatureMaxTime": 1497308400,
                "dewPoint": 44.1,
                "humidity": 0.6,
                "windSpeed": 5.83,
                "windBearing": 266,
                "cloudCover": 0,
                "pressure": 1014.44,
                "ozone": 339.24
            },
            {
                "time": 1497337200,
                "summary": "Clear throughout the day.",
                "icon": "clear-day",
                "sunriseTime": 1497358105,
                "sunsetTime": 1497411239,
                "moonPhase": 0.63,
                "precipIntensity": 0,
                "precipIntensityMax": 0,
                "precipProbability": 0,
                "temperatureMin": 50.28,
                "temperatureMinTime": 1497355200,
                "temperatureMax": 66.64,
                "temperatureMaxTime": 1497394800,
                "apparentTemperatureMin": 50.28,
                "apparentTemperatureMinTime": 1497355200,
                "apparentTemperatureMax": 66.64,
                "apparentTemperatureMaxTime": 1497394800,
                "dewPoint": 45.88,
                "humidity": 0.65,
                "windSpeed": 4.92,
                "windBearing": 247,
                "cloudCover": 0,
                "pressure": 1013.95,
                "ozone": 334.76
            }
        ]
    },
    "flags": {
        "sources": [
            "lamp",
            "gfs",
            "cmc",
            "nam",
            "rap",
            "rtma",
            "sref",
            "fnmoc",
            "isd",
            "madis",
            "nearest-precip",
            "nwspa",
            "darksky"
        ],
        "lamp-stations": [
            "KAPC",
            "KCCR",
            "KHWD",
            "KLVK",
            "KNUQ",
            "KOAK",
            "KPAO",
            "KSFO",
            "KSQL"
        ],
        "isd-stations": [
            "724943-99999",
            "745039-99999",
            "745045-99999",
            "745060-23239",
            "745065-99999",
            "994016-99999",
            "994033-99999",
            "994036-99999",
            "997734-99999",
            "998197-99999",
            "998476-99999",
            "998477-99999",
            "998479-99999",
            "998496-99999",
            "999999-23239",
            "999999-23272"
        ],
        "madis-stations": [
            "AU915",
            "C5988",
            "C8158",
            "CQ147",
            "CQ188",
            "E6067",
            "GGBC1",
            "OKXC1",
            "OMHC1",
            "PPXC1",
            "PXOC1",
            "SFOC1",
            "TIBC1"
        ],
        "units": "us"
    }
}